part of 'battle_combat_stat_service.dart';

const Map<String, BattleCombatStats> _baseStatsByJob =
    <String, BattleCombatStats>{
      CombatJobIds.mercenaryWarrior: BattleCombatStats(
        maxHp: 74,
        maxMp: 8,
        physicalAttack: 16,
        physicalDefense: 13,
        magicalAttack: 5,
        magicalDefense: 9,
        speed: 8,
        critChance: 0.05,
        critDamage: 0.5,
        accuracy: 0.88,
        evasion: 0.04,
        statusAccuracy: 0.04,
        statusResistance: 0.08,
        physicalPenetration: 0.03,
        magicalPenetration: 0.02,
        lifesteal: 0.02,
        healingPower: 0,
        regen: 0.01,
        mpRegen: 2,
      ),
      CombatJobIds.mercenaryMage: BattleCombatStats(
        maxHp: 60,
        maxMp: 10,
        physicalAttack: 5,
        physicalDefense: 8,
        magicalAttack: 18,
        magicalDefense: 11,
        speed: 9,
        critChance: 0.06,
        critDamage: 0.5,
        accuracy: 0.9,
        evasion: 0.05,
        statusAccuracy: 0.12,
        statusResistance: 0.08,
        physicalPenetration: 0.01,
        magicalPenetration: 0.06,
        lifesteal: 0,
        healingPower: 0.05,
        regen: 0.01,
        mpRegen: 3,
      ),
      CombatJobIds.mercenaryRogue: BattleCombatStats(
        maxHp: 62,
        maxMp: 8,
        physicalAttack: 15,
        physicalDefense: 9,
        magicalAttack: 6,
        magicalDefense: 8,
        speed: 13,
        critChance: 0.1,
        critDamage: 0.55,
        accuracy: 0.92,
        evasion: 0.09,
        statusAccuracy: 0.06,
        statusResistance: 0.06,
        physicalPenetration: 0.06,
        magicalPenetration: 0.01,
        lifesteal: 0.03,
        healingPower: 0,
        regen: 0.01,
        mpRegen: 3,
      ),
      CombatJobIds.mercenaryArcher: BattleCombatStats(
        maxHp: 64,
        maxMp: 9,
        physicalAttack: 15,
        physicalDefense: 9,
        magicalAttack: 5,
        magicalDefense: 9,
        speed: 11,
        critChance: 0.08,
        critDamage: 0.55,
        accuracy: 0.95,
        evasion: 0.07,
        statusAccuracy: 0.05,
        statusResistance: 0.06,
        physicalPenetration: 0.05,
        magicalPenetration: 0.01,
        lifesteal: 0.01,
        healingPower: 0,
        regen: 0.01,
        mpRegen: 2,
      ),
      CombatJobIds.homunculusWarrior: BattleCombatStats(
        maxHp: 70,
        maxMp: 8,
        physicalAttack: 14,
        physicalDefense: 12,
        magicalAttack: 8,
        magicalDefense: 11,
        speed: 8,
        critChance: 0.04,
        critDamage: 0.5,
        accuracy: 0.88,
        evasion: 0.04,
        statusAccuracy: 0.05,
        statusResistance: 0.1,
        physicalPenetration: 0.03,
        magicalPenetration: 0.03,
        lifesteal: 0.01,
        healingPower: 0.03,
        regen: 0.02,
        mpRegen: 2,
      ),
      CombatJobIds.homunculusMage: BattleCombatStats(
        maxHp: 62,
        maxMp: 10,
        physicalAttack: 5,
        physicalDefense: 8,
        magicalAttack: 17,
        magicalDefense: 13,
        speed: 9,
        critChance: 0.05,
        critDamage: 0.5,
        accuracy: 0.9,
        evasion: 0.05,
        statusAccuracy: 0.14,
        statusResistance: 0.1,
        physicalPenetration: 0.01,
        magicalPenetration: 0.05,
        lifesteal: 0,
        healingPower: 0.08,
        regen: 0.02,
        mpRegen: 3,
      ),
      CombatJobIds.homunculusRogue: BattleCombatStats(
        maxHp: 60,
        maxMp: 8,
        physicalAttack: 14,
        physicalDefense: 8,
        magicalAttack: 8,
        magicalDefense: 8,
        speed: 14,
        critChance: 0.11,
        critDamage: 0.55,
        accuracy: 0.93,
        evasion: 0.1,
        statusAccuracy: 0.08,
        statusResistance: 0.07,
        physicalPenetration: 0.06,
        magicalPenetration: 0.03,
        lifesteal: 0.02,
        healingPower: 0.02,
        regen: 0.02,
        mpRegen: 3,
      ),
      CombatJobIds.homunculusArcher: BattleCombatStats(
        maxHp: 61,
        maxMp: 9,
        physicalAttack: 14,
        physicalDefense: 8,
        magicalAttack: 7,
        magicalDefense: 9,
        speed: 12,
        critChance: 0.09,
        critDamage: 0.55,
        accuracy: 0.96,
        evasion: 0.08,
        statusAccuracy: 0.06,
        statusResistance: 0.07,
        physicalPenetration: 0.05,
        magicalPenetration: 0.02,
        lifesteal: 0.01,
        healingPower: 0.02,
        regen: 0.02,
        mpRegen: 2,
      ),
    };

const Map<String, BattleCombatStats> _tierGrowthByJob =
    <String, BattleCombatStats>{
      CombatJobIds.mercenaryWarrior: BattleCombatStats(
        maxHp: 24,
        maxMp: 1,
        physicalAttack: 4,
        physicalDefense: 4,
        magicalAttack: 1,
        magicalDefense: 3,
        speed: 1,
        critChance: 0.005,
        critDamage: 0.02,
        accuracy: 0.005,
        evasion: 0.003,
        statusAccuracy: 0.003,
        statusResistance: 0.01,
        physicalPenetration: 0.004,
        magicalPenetration: 0.002,
        lifesteal: 0.002,
        healingPower: 0,
        regen: 0.003,
      ),
      CombatJobIds.mercenaryMage: BattleCombatStats(
        maxHp: 20,
        maxMp: 2,
        physicalAttack: 1,
        physicalDefense: 2,
        magicalAttack: 5,
        magicalDefense: 4,
        speed: 1,
        critChance: 0.005,
        critDamage: 0.02,
        accuracy: 0.006,
        evasion: 0.003,
        statusAccuracy: 0.01,
        statusResistance: 0.01,
        physicalPenetration: 0.001,
        magicalPenetration: 0.005,
        lifesteal: 0,
        healingPower: 0.01,
        regen: 0.003,
      ),
      CombatJobIds.mercenaryRogue: BattleCombatStats(
        maxHp: 18,
        maxMp: 1,
        physicalAttack: 4,
        physicalDefense: 1,
        magicalAttack: 1,
        magicalDefense: 1,
        speed: 2,
        critChance: 0.01,
        critDamage: 0.02,
        accuracy: 0.01,
        evasion: 0.01,
        statusAccuracy: 0.004,
        statusResistance: 0.005,
        physicalPenetration: 0.005,
        magicalPenetration: 0.001,
        lifesteal: 0.003,
        healingPower: 0,
        regen: 0.002,
      ),
      CombatJobIds.mercenaryArcher: BattleCombatStats(
        maxHp: 18,
        maxMp: 1,
        physicalAttack: 4,
        physicalDefense: 1,
        magicalAttack: 1,
        magicalDefense: 2,
        speed: 2,
        critChance: 0.008,
        critDamage: 0.02,
        accuracy: 0.012,
        evasion: 0.007,
        statusAccuracy: 0.004,
        statusResistance: 0.005,
        physicalPenetration: 0.005,
        magicalPenetration: 0.001,
        lifesteal: 0.001,
        healingPower: 0,
        regen: 0.002,
      ),
      CombatJobIds.homunculusWarrior: BattleCombatStats(
        maxHp: 22,
        maxMp: 1,
        physicalAttack: 3,
        physicalDefense: 4,
        magicalAttack: 2,
        magicalDefense: 4,
        speed: 1,
        critChance: 0.004,
        critDamage: 0.02,
        accuracy: 0.005,
        evasion: 0.003,
        statusAccuracy: 0.004,
        statusResistance: 0.012,
        physicalPenetration: 0.003,
        magicalPenetration: 0.003,
        lifesteal: 0.001,
        healingPower: 0.005,
        regen: 0.004,
      ),
      CombatJobIds.homunculusMage: BattleCombatStats(
        maxHp: 20,
        maxMp: 2,
        physicalAttack: 1,
        physicalDefense: 2,
        magicalAttack: 4,
        magicalDefense: 4,
        speed: 1,
        critChance: 0.004,
        critDamage: 0.02,
        accuracy: 0.006,
        evasion: 0.004,
        statusAccuracy: 0.012,
        statusResistance: 0.012,
        physicalPenetration: 0.001,
        magicalPenetration: 0.005,
        lifesteal: 0,
        healingPower: 0.012,
        regen: 0.004,
      ),
      CombatJobIds.homunculusRogue: BattleCombatStats(
        maxHp: 18,
        maxMp: 1,
        physicalAttack: 3,
        physicalDefense: 1,
        magicalAttack: 2,
        magicalDefense: 1,
        speed: 2,
        critChance: 0.01,
        critDamage: 0.02,
        accuracy: 0.01,
        evasion: 0.012,
        statusAccuracy: 0.006,
        statusResistance: 0.006,
        physicalPenetration: 0.004,
        magicalPenetration: 0.003,
        lifesteal: 0.002,
        healingPower: 0.004,
        regen: 0.004,
      ),
      CombatJobIds.homunculusArcher: BattleCombatStats(
        maxHp: 18,
        maxMp: 1,
        physicalAttack: 3,
        physicalDefense: 1,
        magicalAttack: 2,
        magicalDefense: 2,
        speed: 2,
        critChance: 0.008,
        critDamage: 0.02,
        accuracy: 0.012,
        evasion: 0.008,
        statusAccuracy: 0.005,
        statusResistance: 0.006,
        physicalPenetration: 0.004,
        magicalPenetration: 0.002,
        lifesteal: 0.001,
        healingPower: 0.004,
        regen: 0.004,
      ),
    };

const Map<String, BattleCombatStats> _rankGrowthByJob =
    <String, BattleCombatStats>{
      CombatJobIds.mercenaryWarrior: BattleCombatStats(
        maxHp: 18,
        maxMp: 1,
        physicalAttack: 3,
        physicalDefense: 3,
        magicalAttack: 1,
        magicalDefense: 2,
        speed: 1,
        critChance: 0.005,
        critDamage: 0.02,
        accuracy: 0.004,
        evasion: 0.002,
        statusAccuracy: 0.002,
        statusResistance: 0.006,
        physicalPenetration: 0.003,
        magicalPenetration: 0.001,
        lifesteal: 0.001,
        healingPower: 0,
        regen: 0.002,
      ),
      CombatJobIds.mercenaryMage: BattleCombatStats(
        maxHp: 15,
        maxMp: 1,
        physicalAttack: 1,
        physicalDefense: 1,
        magicalAttack: 4,
        magicalDefense: 3,
        speed: 1,
        critChance: 0.005,
        critDamage: 0.02,
        accuracy: 0.004,
        evasion: 0.002,
        statusAccuracy: 0.008,
        statusResistance: 0.006,
        physicalPenetration: 0.001,
        magicalPenetration: 0.004,
        lifesteal: 0,
        healingPower: 0.008,
        regen: 0.002,
      ),
      CombatJobIds.mercenaryRogue: BattleCombatStats(
        maxHp: 14,
        maxMp: 1,
        physicalAttack: 3,
        physicalDefense: 1,
        magicalAttack: 1,
        magicalDefense: 1,
        speed: 2,
        critChance: 0.01,
        critDamage: 0.02,
        accuracy: 0.008,
        evasion: 0.01,
        statusAccuracy: 0.004,
        statusResistance: 0.004,
        physicalPenetration: 0.004,
        magicalPenetration: 0.001,
        lifesteal: 0.002,
        healingPower: 0,
        regen: 0.001,
      ),
      CombatJobIds.mercenaryArcher: BattleCombatStats(
        maxHp: 14,
        maxMp: 1,
        physicalAttack: 3,
        physicalDefense: 1,
        magicalAttack: 1,
        magicalDefense: 2,
        speed: 1,
        critChance: 0.008,
        critDamage: 0.02,
        accuracy: 0.01,
        evasion: 0.006,
        statusAccuracy: 0.003,
        statusResistance: 0.004,
        physicalPenetration: 0.004,
        magicalPenetration: 0.001,
        lifesteal: 0.001,
        healingPower: 0,
        regen: 0.001,
      ),
      CombatJobIds.homunculusWarrior: BattleCombatStats(
        maxHp: 16,
        maxMp: 1,
        physicalAttack: 2,
        physicalDefense: 3,
        magicalAttack: 2,
        magicalDefense: 3,
        speed: 1,
        critChance: 0.004,
        critDamage: 0.02,
        accuracy: 0.004,
        evasion: 0.002,
        statusAccuracy: 0.003,
        statusResistance: 0.007,
        physicalPenetration: 0.002,
        magicalPenetration: 0.002,
        lifesteal: 0.001,
        healingPower: 0.004,
        regen: 0.003,
      ),
      CombatJobIds.homunculusMage: BattleCombatStats(
        maxHp: 14,
        maxMp: 1,
        physicalAttack: 1,
        physicalDefense: 1,
        magicalAttack: 3,
        magicalDefense: 3,
        speed: 1,
        critChance: 0.004,
        critDamage: 0.02,
        accuracy: 0.004,
        evasion: 0.002,
        statusAccuracy: 0.008,
        statusResistance: 0.007,
        physicalPenetration: 0.001,
        magicalPenetration: 0.004,
        lifesteal: 0,
        healingPower: 0.008,
        regen: 0.003,
      ),
      CombatJobIds.homunculusRogue: BattleCombatStats(
        maxHp: 13,
        maxMp: 1,
        physicalAttack: 2,
        physicalDefense: 1,
        magicalAttack: 2,
        magicalDefense: 1,
        speed: 2,
        critChance: 0.01,
        critDamage: 0.02,
        accuracy: 0.008,
        evasion: 0.01,
        statusAccuracy: 0.004,
        statusResistance: 0.004,
        physicalPenetration: 0.003,
        magicalPenetration: 0.002,
        lifesteal: 0.001,
        healingPower: 0.003,
        regen: 0.003,
      ),
      CombatJobIds.homunculusArcher: BattleCombatStats(
        maxHp: 13,
        maxMp: 1,
        physicalAttack: 2,
        physicalDefense: 1,
        magicalAttack: 2,
        magicalDefense: 1,
        speed: 1,
        critChance: 0.008,
        critDamage: 0.02,
        accuracy: 0.01,
        evasion: 0.006,
        statusAccuracy: 0.003,
        statusResistance: 0.004,
        physicalPenetration: 0.003,
        magicalPenetration: 0.001,
        lifesteal: 0.001,
        healingPower: 0.003,
        regen: 0.003,
      ),
    };

const Map<String, List<BattleSkillDefinition>> _skillsByJob =
    <String, List<BattleSkillDefinition>>{
      CombatJobIds.mercenaryWarrior: <BattleSkillDefinition>[
        BattleSkillDefinition(
          id: 'mercenary_warrior_shield_break',
          name: '방패 강타',
          summary: '강한 일격으로 무작위 적에게 물리 피해를 준다.',
          targetType: BattleSkillTargetType.randomEnemy,
          effectType: BattleSkillEffectType.damage,
          school: DamageSchool.physical,
          powerMultiplier: 1.45,
          flatPower: 4,
        ),
      ],
      CombatJobIds.mercenaryMage: <BattleSkillDefinition>[
        BattleSkillDefinition(
          id: 'mercenary_mage_fireball',
          name: '화염구',
          summary: '압축한 화염으로 모든 적에게 마법 피해를 준다.',
          targetType: BattleSkillTargetType.allEnemies,
          effectType: BattleSkillEffectType.damage,
          school: DamageSchool.magical,
          powerMultiplier: 0.95,
          flatPower: 4,
        ),
      ],
      CombatJobIds.mercenaryRogue: <BattleSkillDefinition>[
        BattleSkillDefinition(
          id: 'mercenary_rogue_expose',
          name: '약점 노출',
          summary: '무작위 적이 받는 피해를 잠시 증가시킨다.',
          targetType: BattleSkillTargetType.randomEnemy,
          effectType: BattleSkillEffectType.grantModifier,
          durationLifecycles: 2,
          modifier: BattleModifier(
            type: BattleModifierType.damageTaken,
            mode: BattleModifierMode.percent,
            value: 0.16,
            sourceId: 'mercenary_rogue_expose',
          ),
        ),
      ],
      CombatJobIds.mercenaryArcher: <BattleSkillDefinition>[
        BattleSkillDefinition(
          id: 'mercenary_archer_piercing_shot',
          name: '관통 사격',
          summary: '방어선을 꿰뚫는 화살로 무작위 적에게 물리 피해를 준다.',
          targetType: BattleSkillTargetType.randomEnemy,
          effectType: BattleSkillEffectType.damage,
          school: DamageSchool.physical,
          powerMultiplier: 1.55,
          flatPower: 3,
        ),
      ],
      CombatJobIds.homunculusWarrior: <BattleSkillDefinition>[
        BattleSkillDefinition(
          id: 'homunculus_warrior_bio_guard',
          name: '생체 장갑',
          summary: '자신에게 보호막을 부여한다.',
          targetType: BattleSkillTargetType.self,
          effectType: BattleSkillEffectType.grantShield,
          shieldValue: 18,
        ),
      ],
      CombatJobIds.homunculusMage: <BattleSkillDefinition>[
        BattleSkillDefinition(
          id: 'homunculus_mage_reconstruct',
          name: '재구성',
          summary: '모든 아군의 체력을 회복한다.',
          targetType: BattleSkillTargetType.allAllies,
          effectType: BattleSkillEffectType.heal,
          flatPower: 12,
        ),
      ],
      CombatJobIds.homunculusRogue: <BattleSkillDefinition>[
        BattleSkillDefinition(
          id: 'homunculus_rogue_acid_infusion',
          name: '산성 주입',
          summary: '무작위 적에게 독을 부여한다.',
          targetType: BattleSkillTargetType.randomEnemy,
          effectType: BattleSkillEffectType.grantStatus,
          statusType: BattleStatusType.poison,
          durationLifecycles: 3,
          flatPower: 5,
        ),
      ],
      CombatJobIds.homunculusArcher: <BattleSkillDefinition>[
        BattleSkillDefinition(
          id: 'homunculus_archer_resonance_shot',
          name: '공명 사격',
          summary: '모든 적에게 마법 피해를 준다.',
          targetType: BattleSkillTargetType.allEnemies,
          effectType: BattleSkillEffectType.damage,
          school: DamageSchool.magical,
          powerMultiplier: 0.9,
          flatPower: 4,
        ),
      ],
    };

const Map<String, int> _levelHpGrowthByJob = <String, int>{
  CombatJobIds.mercenaryWarrior: 14,
  CombatJobIds.mercenaryMage: 10,
  CombatJobIds.mercenaryRogue: 11,
  CombatJobIds.mercenaryArcher: 11,
  CombatJobIds.homunculusWarrior: 12,
  CombatJobIds.homunculusMage: 11,
  CombatJobIds.homunculusRogue: 10,
  CombatJobIds.homunculusArcher: 10,
};
